on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, flowflex-prod-v2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy docker-compose.env file to base folder
        run: cp ../docker-compose.env ./docker-compose.env
      - name: Install dependencies
        run: npm install
      - name: Bring up Docker containers
        run: npm run dc:up
